### PR TITLE
three pages were added one for assigning exercise for each user and o…

### PR DESCRIPTION
**Pull request by Laurence-AGS**
…ne for coach assigned users the third one is for describtion of each exercise and illustration video

### CODE REVIEW

**Review by marksamfd — APPROVED** [review]
Approved, Well Done

**Comment by sherifAAM** [comment]
approved

**Review by sherifAAM — APPROVED** [review]

**Comment by marksamfd** [comment]
fixed #7

**Comment by marksamfd** [comment]
fixed #2

**Pull request merged**
